<?xml version="1.0" ?>

<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                              xmlns:ipfix="urn:ietf:params:xml:ns:yang:ietf-ipfix-psamp">
    <xsl:strip-space elements="*"/>
    <xsl:output method="xml" encoding="UTF-8" indent="yes"/>
    <xsl:param name="ipfix_ns" select="'urn:ietf:params:xml:ns:yang:ietf-ipfix-psamp'" />





   <!-- Delete cacheField if underlying ieName is set to an unsupported xpath -->
   <xsl:template match="ipfix:ipfix/ipfix:cache/ipfix:permanentCache/ipfix:cacheLayout/ipfix:cacheField[
                          ipfix:ieName[
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:up-time' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:total-active-process' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:run-process' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:sleep-process' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:stop-process' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:zombie-process' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:active-session' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:cpu-avg-load-1-min' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:cpu-avg-load-5-min' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:cpu-avg-load-15-mins' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:percent-cpu-hwio' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:percent-cpu-io' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:percent-cpu-nice' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:percent-cpu-swint' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:percent-cpu-system' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:percent-cpu-unused' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:percent-cpu-user' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:buffer-mem-system' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:free-mem-system' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:total-mem-system' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:used-mem-system' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:available-mem-system' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/nokia-ipfix:username' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/nokia-ipfix:password' or
                                      text()='/ipfix:ipfix/nokia-ipfix:collection-timestamp' or
                                      text()='/ipfix:ipfix/nokia-ipfix:last-message' or
                                      text()='/ipfix:ipfix/nokia-ipfix:cache-sequence-number' or
                                      text()='/ipfix:ipfix/nokia-ipfix:record-type' or
                                      text()='/ipfix:ipfix/nokia-ipfix:delete-flag' or
                                      text()='/ipfix:ipfix/nokia-ipfix:data-presence-indication' or
                                      text()='/ipfix:ipfix/nokia-ipfix:hierarchy-meta-info' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:ipfixVersion' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:destinationAddress' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:destinationPort' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:status' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:bytes' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:messages' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:discardedMessages' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:records' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:templates' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:optionsTemplates' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:transportSessionStartTime' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:transportSessionDiscontinuityTime' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:template' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:template/ipfix:templateId' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:template/ipfix:accessTime' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:template/ipfix:templateDataRecords' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:template/ipfix:templateDiscontinuityTime' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:name' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:name' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:ltr-transaction-id' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:linktrace-input' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-receive-order' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-ttl' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-forwarded' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-terminal-mep' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-last-egress-identifier' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-next-egress-identifier' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-relay' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-chassis-id-subtype' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-chassis-id' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-transport-service-domain' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-ingress' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-ingress-mac' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-ingress-port-id-subtype' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-ingress-port-id' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-egress' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-egress-mac' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-egress-port-id-subtype' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-egress-port-id' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-organization-specific-tlv' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/nokia-cfm-linktrace:status' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/nokia-cfm-linktrace:reason' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:status' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:reason' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:transaction-id' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:lbm-dest-ucast-mac-address' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:message-interval' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:vlan-tag-info' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:pattern-tlv' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:number-of-messages' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:statistics' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:transmit-loopback-discover-response/nokia-cfm-loopback:response' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:stats/dot1q-cfm:mep-lbr-in' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:stats/dot1q-cfm:mep-lbr-in-out-of-order' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:stats/dot1q-cfm:mep-lbr-bad-msdu' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:stats/dot1q-cfm:mep-unexpected-ltr-in' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:linktrace-input/dot1q-cfm:ltm-target-mac-address' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:linktrace-input/dot1q-cfm:ltm-ttl' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:linktrace-input/dot1q-cfm:ltm-flags' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-last-egress-identifier/dot1q-cfm:int' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-last-egress-identifier/dot1q-cfm:address' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-next-egress-identifier/dot1q-cfm:int' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-next-egress-identifier/dot1q-cfm:address' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-transport-service-domain/dot1q-cfm:domain' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-transport-service-domain/dot1q-cfm:ip-address' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-transport-service-domain/dot1q-cfm:ip-port' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-transport-service-domain/dot1q-cfm:local-address' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-transport-service-domain/dot1q-cfm:dns-address' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-transport-service-domain/dot1q-cfm:unknown-address' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:vlan-tag-info/nokia-cfm-loopback:outer-tag-priority' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:vlan-tag-info/nokia-cfm-loopback:inner-tag-priority' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:vlan-tag-info/nokia-cfm-loopback:outer-tag-drop-eligible' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:vlan-tag-info/nokia-cfm-loopback:inner-tag-drop-eligible' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:pattern-tlv/nokia-cfm-loopback:data-tlv' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:pattern-tlv/nokia-cfm-loopback:tlv-length' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:statistics/nokia-cfm-loopback:in-lbr' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:statistics/nokia-cfm-loopback:in-lbr-out-of-order' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:statistics/nokia-cfm-loopback:in-lbr-bad-msdu' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:statistics/nokia-cfm-loopback:out-lbm' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:transmit-loopback-discover-response/nokia-cfm-loopback:response/nokia-cfm-loopback:receive-order' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:transmit-loopback-discover-response/nokia-cfm-loopback:response/nokia-cfm-loopback:reply-mac-address'
                          ]
   ]"/>



   <!-- Delete cache if the count of the underlying ieNames equals to the count of ieNames that contain
                unsupported xpaths, i.e, not even 1 supported xpath is present in the cache. -->
   <xsl:template match="ipfix:ipfix/ipfix:cache[
                          count(./ipfix:permanentCache/ipfix:cacheLayout/ipfix:cacheField/ipfix:ieName) > 0 and
                          count(./ipfix:permanentCache/ipfix:cacheLayout/ipfix:cacheField/ipfix:ieName) =
                          count(./ipfix:permanentCache/ipfix:cacheLayout/ipfix:cacheField/ipfix:ieName[
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:up-time' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:total-active-process' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:run-process' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:sleep-process' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:stop-process' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:zombie-process' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:active-session' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:cpu-avg-load-1-min' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:cpu-avg-load-5-min' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:cpu-avg-load-15-mins' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:percent-cpu-hwio' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:percent-cpu-io' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:percent-cpu-nice' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:percent-cpu-swint' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:percent-cpu-system' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:percent-cpu-unused' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:percent-cpu-user' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:buffer-mem-system' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:free-mem-system' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:total-mem-system' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:used-mem-system' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:available-mem-system' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/nokia-ipfix:username' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/nokia-ipfix:password' or
                                      text()='/ipfix:ipfix/nokia-ipfix:collection-timestamp' or
                                      text()='/ipfix:ipfix/nokia-ipfix:last-message' or
                                      text()='/ipfix:ipfix/nokia-ipfix:cache-sequence-number' or
                                      text()='/ipfix:ipfix/nokia-ipfix:record-type' or
                                      text()='/ipfix:ipfix/nokia-ipfix:delete-flag' or
                                      text()='/ipfix:ipfix/nokia-ipfix:data-presence-indication' or
                                      text()='/ipfix:ipfix/nokia-ipfix:hierarchy-meta-info' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:ipfixVersion' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:destinationAddress' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:destinationPort' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:status' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:bytes' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:messages' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:discardedMessages' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:records' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:templates' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:optionsTemplates' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:transportSessionStartTime' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:transportSessionDiscontinuityTime' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:template' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:template/ipfix:templateId' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:template/ipfix:accessTime' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:template/ipfix:templateDataRecords' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:template/ipfix:templateDiscontinuityTime' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:name' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:name' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:ltr-transaction-id' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:linktrace-input' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-receive-order' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-ttl' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-forwarded' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-terminal-mep' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-last-egress-identifier' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-next-egress-identifier' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-relay' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-chassis-id-subtype' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-chassis-id' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-transport-service-domain' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-ingress' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-ingress-mac' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-ingress-port-id-subtype' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-ingress-port-id' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-egress' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-egress-mac' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-egress-port-id-subtype' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-egress-port-id' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-organization-specific-tlv' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/nokia-cfm-linktrace:status' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/nokia-cfm-linktrace:reason' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:status' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:reason' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:transaction-id' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:lbm-dest-ucast-mac-address' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:message-interval' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:vlan-tag-info' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:pattern-tlv' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:number-of-messages' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:statistics' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:transmit-loopback-discover-response/nokia-cfm-loopback:response' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:stats/dot1q-cfm:mep-lbr-in' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:stats/dot1q-cfm:mep-lbr-in-out-of-order' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:stats/dot1q-cfm:mep-lbr-bad-msdu' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:stats/dot1q-cfm:mep-unexpected-ltr-in' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:linktrace-input/dot1q-cfm:ltm-target-mac-address' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:linktrace-input/dot1q-cfm:ltm-ttl' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:linktrace-input/dot1q-cfm:ltm-flags' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-last-egress-identifier/dot1q-cfm:int' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-last-egress-identifier/dot1q-cfm:address' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-next-egress-identifier/dot1q-cfm:int' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-next-egress-identifier/dot1q-cfm:address' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-transport-service-domain/dot1q-cfm:domain' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-transport-service-domain/dot1q-cfm:ip-address' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-transport-service-domain/dot1q-cfm:ip-port' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-transport-service-domain/dot1q-cfm:local-address' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-transport-service-domain/dot1q-cfm:dns-address' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-transport-service-domain/dot1q-cfm:unknown-address' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:vlan-tag-info/nokia-cfm-loopback:outer-tag-priority' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:vlan-tag-info/nokia-cfm-loopback:inner-tag-priority' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:vlan-tag-info/nokia-cfm-loopback:outer-tag-drop-eligible' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:vlan-tag-info/nokia-cfm-loopback:inner-tag-drop-eligible' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:pattern-tlv/nokia-cfm-loopback:data-tlv' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:pattern-tlv/nokia-cfm-loopback:tlv-length' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:statistics/nokia-cfm-loopback:in-lbr' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:statistics/nokia-cfm-loopback:in-lbr-out-of-order' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:statistics/nokia-cfm-loopback:in-lbr-bad-msdu' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:statistics/nokia-cfm-loopback:out-lbm' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:transmit-loopback-discover-response/nokia-cfm-loopback:response/nokia-cfm-loopback:receive-order' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:transmit-loopback-discover-response/nokia-cfm-loopback:response/nokia-cfm-loopback:reply-mac-address'
                          ])
   ]"/>


   <!-- xsl rule to remove ipfix elements -->
   <xsl:template match="ipfix:ipfix[
                          count(./ipfix:randomize-data-collection) = 0 and
                          count(./ipfix:ipfix-exporting-enable) = 0 and
                          count(./exportingProcess) = 0 and
                          (count(./ipfix:cache) = 0 or
                          count(./ipfix:cache/ipfix:permanentCache/ipfix:cacheLayout/ipfix:cacheField/ipfix:ieName) > 0 and
                          count(./ipfix:cache/ipfix:permanentCache/ipfix:cacheLayout/ipfix:cacheField/ipfix:ieName) = count(./ipfix:cache/ipfix:permanentCache/ipfix:cacheLayout/ipfix:cacheField/ipfix:ieName[
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:up-time' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:total-active-process' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:run-process' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:sleep-process' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:stop-process' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:zombie-process' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:active-session' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:cpu-avg-load-1-min' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:cpu-avg-load-5-min' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:cpu-avg-load-15-mins' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:percent-cpu-hwio' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:percent-cpu-io' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:percent-cpu-nice' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:percent-cpu-swint' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:percent-cpu-system' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:percent-cpu-unused' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:percent-cpu-user' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:buffer-mem-system' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:free-mem-system' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:total-mem-system' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:used-mem-system' or
                                      text()='/hw:hardware-state/hw:component/bbf-hw-resource:resource-data/bbf-hw-resource:available-mem-system' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/nokia-ipfix:username' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/nokia-ipfix:password' or
                                      text()='/ipfix:ipfix/nokia-ipfix:collection-timestamp' or
                                      text()='/ipfix:ipfix/nokia-ipfix:last-message' or
                                      text()='/ipfix:ipfix/nokia-ipfix:cache-sequence-number' or
                                      text()='/ipfix:ipfix/nokia-ipfix:record-type' or
                                      text()='/ipfix:ipfix/nokia-ipfix:delete-flag' or
                                      text()='/ipfix:ipfix/nokia-ipfix:data-presence-indication' or
                                      text()='/ipfix:ipfix/nokia-ipfix:hierarchy-meta-info' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:ipfixVersion' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:destinationAddress' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:destinationPort' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:status' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:bytes' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:messages' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:discardedMessages' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:records' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:templates' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:optionsTemplates' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:transportSessionStartTime' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:transportSessionDiscontinuityTime' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:template' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:template/ipfix:templateId' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:template/ipfix:accessTime' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:template/ipfix:templateDataRecords' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:tcpExporter/ipfix:transportSession/ipfix:template/ipfix:templateDiscontinuityTime' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:name' or
                                      text()='/ipfix:ipfix/ipfix:exportingProcess/ipfix:destination/ipfix:name' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:ltr-transaction-id' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:linktrace-input' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-receive-order' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-ttl' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-forwarded' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-terminal-mep' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-last-egress-identifier' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-next-egress-identifier' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-relay' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-chassis-id-subtype' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-chassis-id' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-transport-service-domain' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-ingress' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-ingress-mac' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-ingress-port-id-subtype' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-ingress-port-id' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-egress' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-egress-mac' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-egress-port-id-subtype' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-egress-port-id' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-organization-specific-tlv' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/nokia-cfm-linktrace:status' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/nokia-cfm-linktrace:reason' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:status' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:reason' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:transaction-id' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:lbm-dest-ucast-mac-address' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:message-interval' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:vlan-tag-info' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:pattern-tlv' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:number-of-messages' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:statistics' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:transmit-loopback-discover-response/nokia-cfm-loopback:response' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:stats/dot1q-cfm:mep-lbr-in' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:stats/dot1q-cfm:mep-lbr-in-out-of-order' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:stats/dot1q-cfm:mep-lbr-bad-msdu' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:stats/dot1q-cfm:mep-unexpected-ltr-in' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:linktrace-input/dot1q-cfm:ltm-target-mac-address' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:linktrace-input/dot1q-cfm:ltm-ttl' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:linktrace-input/dot1q-cfm:ltm-flags' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-last-egress-identifier/dot1q-cfm:int' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-last-egress-identifier/dot1q-cfm:address' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-next-egress-identifier/dot1q-cfm:int' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-next-egress-identifier/dot1q-cfm:address' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-transport-service-domain/dot1q-cfm:domain' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-transport-service-domain/dot1q-cfm:ip-address' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-transport-service-domain/dot1q-cfm:ip-port' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-transport-service-domain/dot1q-cfm:local-address' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-transport-service-domain/dot1q-cfm:dns-address' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/dot1q-cfm:linktrace-reply/dot1q-cfm:responses/dot1q-cfm:ltr-transport-service-domain/dot1q-cfm:unknown-address' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:vlan-tag-info/nokia-cfm-loopback:outer-tag-priority' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:vlan-tag-info/nokia-cfm-loopback:inner-tag-priority' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:vlan-tag-info/nokia-cfm-loopback:outer-tag-drop-eligible' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:vlan-tag-info/nokia-cfm-loopback:inner-tag-drop-eligible' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:pattern-tlv/nokia-cfm-loopback:data-tlv' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:pattern-tlv/nokia-cfm-loopback:tlv-length' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:statistics/nokia-cfm-loopback:in-lbr' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:statistics/nokia-cfm-loopback:in-lbr-out-of-order' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:statistics/nokia-cfm-loopback:in-lbr-bad-msdu' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:statistics/nokia-cfm-loopback:out-lbm' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:transmit-loopback-discover-response/nokia-cfm-loopback:response/nokia-cfm-loopback:receive-order' or
                                      text()='/dot1q-cfm:cfm/dot1q-cfm:maintenance-group/dot1q-cfm:mep/nokia-cfm-loopback:loopback-transmit-session/nokia-cfm-loopback:transmit-loopback-discover-response/nokia-cfm-loopback:response/nokia-cfm-loopback:reply-mac-address'
                          ]))
   ]"/>




</xsl:stylesheet>