# Nacos Configuration for lens-platform-system
# Namespace: lens_2026
# Group: DEFAULT_GROUP
# Data ID: lens-platform-system.yaml
#
# Environment variables required:
# - SYSTEM_PORT, JWT_JWK_SET_URI, KEYCLOAK_URL, KEYCLOAK_REALM, OPENAPI_VERSION
# - LOG_LEVEL_ROOT, LOG_LEVEL_LENS, LOG_LEVEL_SPRING_SECURITY

server:
  port: ${SYSTEM_PORT:8042}
  # Disable forward headers strategy to prevent Springdoc from detecting gateway prefix
  # We handle the prefix in OpenAPI configuration via openapi.service.url
  forward-headers-strategy: none
  # Alternative for older Spring Boot versions: use tomcat configuration
  tomcat:
    redirect-context-root: false
    use-relative-redirects: true

spring:
  application:
    name: lens-platform-system

  # Security & OAuth2 JWT Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          # JWK Set URI - used to fetch public keys for JWT validation
          # This approach avoids connecting to Keycloak during application startup
          jwk-set-uri: ${JWT_JWK_SET_URI:http://172.28.0.1:28080/realms/lens/protocol/openid-connect/certs}
          # Alternative: Use issuer-uri (connects at startup to fetch OIDC config)
          # issuer-uri: ${JWT_ISSUER_URI:http://172.28.0.1:28080/realms/lens}

# OpenAPI Configuration
openapi:
  service:
    title: Lens Platform System API
    version: ${OPENAPI_VERSION:2.0.0}
    # Use gateway URL for Swagger UI API calls to avoid CORS issues
    url: ${SYSTEM_URL:http://localhost:8050/v2/lens/platform/system}

# Springdoc Configuration for Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    # Configure Swagger UI to use the full gateway URL for API docs
    # This prevents relative path resolution issues
    url: /v2/lens/platform/system/v3/api-docs
    config-url: /v2/lens/platform/system/v3/api-docs/swagger-config
    # OAuth2 configuration - client credentials pre-configured
    oauth2-redirect-url: http://localhost:8050/v2/lens/platform/system/swagger-ui/oauth2-redirect.html
    oauth:
      client-id: lens-client
      client-secret: x6lEH0DMcT27eop2cszIP3Brc2sDQHLb
      # Use PKCE for better security with authorization code flow
      use-pkce-with-authorization-code-grant: true
      # Scopes to request
      scopes:
        - openid
        - profile
        - email
  disable-swagger-default-url: false
  pre-loading-enabled: false

# Keycloak Configuration
keycloak:
  url: ${KEYCLOAK_URL:http://172.28.0.1:28080}
  realm: ${KEYCLOAK_REALM:lens}

# Logging Configuration
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.lens: ${LOG_LEVEL_LENS:DEBUG}
    org.springframework.security: ${LOG_LEVEL_SPRING_SECURITY:DEBUG}

# Management & Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
